language: python

# Define testing environment
os:
    - linux

env:
    global:
        # Package to be tested
        - PACKAGE="sublime-vertical-sync"
    matrix:
        - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

# Define pre-reqs
before_install:
    # Fetch the travis.sh bootstrapper file from the UnitTesting git repo
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    # Bootstrap the env
    - sh travis.sh bootstrap

# Define what we want to test
script:
    - sh travis.sh run_tests

# Dont send emails unless things are blowing up (or getting better)
notifications:
    email:
        on_success: change
        on_failure: always
